---
abstract: 'a simple configuration module based on XML'
author:
  - 'Jonas B. Nielsen <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Conf
requires:
  Carp: 0
  Data::Dumper: 0
  Test::Harness: 0
  Test::More: 0
  Tie::DeepTied: 0
  Tie::Hash: 0
  Tie::Tools: 1.05
  XML::Simple: 2.20
  perl: 5.008
version: 0.06
